apiVersion: v1
kind: ServiceAccount
metadata:
  name: jit-operator
  namespace: jit-system
  labels:
    app.kubernetes.io/name: jit-operator
    app.kubernetes.io/component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jit-operator-manager-role
  labels:
    app.kubernetes.io/name: jit-operator
    app.kubernetes.io/component: rbac
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jit.rebelops.io
  resources:
  - jitaccessjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jit.rebelops.io
  resources:
  - jitaccessjobs/finalizers
  verbs:
  - update
- apiGroups:
  - jit.rebelops.io
  resources:
  - jitaccessjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jit.rebelops.io
  resources:
  - jitaccessrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jit.rebelops.io
  resources:
  - jitaccessrequests/finalizers
  verbs:
  - update
- apiGroups:
  - jit.rebelops.io
  resources:
  - jitaccessrequests/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jit-operator-manager-rolebinding
  labels:
    app.kubernetes.io/name: jit-operator
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jit-operator-manager-role
subjects:
- kind: ServiceAccount
  name: jit-operator
  namespace: jit-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jit-operator-leader-election-role
  namespace: jit-system
  labels:
    app.kubernetes.io/name: jit-operator
    app.kubernetes.io/component: rbac
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jit-operator-leader-election-rolebinding
  namespace: jit-system
  labels:
    app.kubernetes.io/name: jit-operator
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jit-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: jit-operator
  namespace: jit-system