version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.24"

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    govet:
      enable:
        - shadow
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - errcheck
          - gosec