run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - unused
    - gosimple
    - gosec
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - goprintffuncname
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gofumpt:
    lang-version: "1.24"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0