---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: jit-bot-validating-webhook
  namespace: jit-system
spec:
  clientConfig:
    service:
      name: jit-operator-webhook-service
      namespace: jit-system
      path: "/validate-jit-rebelops-io-v1alpha1-jitaccessrequest"
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["jit.rebelops.io"]
    apiVersions: ["v1alpha1"]
    resources: ["jitaccessrequests"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionWebhook
metadata:
  name: jit-bot-mutating-webhook
  namespace: jit-system
spec:
  clientConfig:
    service:
      name: jit-operator-webhook-service
      namespace: jit-system
      path: "/mutate-jit-rebelops-io-v1alpha1-jitaccessrequest"
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["jit.rebelops.io"]
    apiVersions: ["v1alpha1"]
    resources: ["jitaccessrequests"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionWebhook
metadata:
  name: jit-bot-job-mutating-webhook
  namespace: jit-system
spec:
  clientConfig:
    service:
      name: jit-operator-webhook-service
      namespace: jit-system
      path: "/mutate-jit-rebelops-io-v1alpha1-jitaccessjob"
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["jit.rebelops.io"]
    apiVersions: ["v1alpha1"]
    resources: ["jitaccessjobs"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail

---
apiVersion: v1
kind: Service
metadata:
  name: jit-operator-webhook-service
  namespace: jit-system
spec:
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: jit-operator

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jit-operator-serving-cert
  namespace: jit-system
spec:
  dnsNames:
  - jit-operator-webhook-service.jit-system.svc
  - jit-operator-webhook-service.jit-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: jit-operator-selfsigned-issuer
  secretName: jit-operator-webhook-certs

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: jit-operator-selfsigned-issuer
  namespace: jit-system
spec:
  selfSigned: {}

---
# If not using cert-manager, create self-signed certificate manually
apiVersion: v1
kind: Secret
metadata:
  name: jit-operator-webhook-certs
  namespace: jit-system
type: kubernetes.io/tls
data:
  # These will be generated by cert-manager or manually created
  tls.crt: ""
  tls.key: ""