{{- if and .Values.secrets.slack.botToken .Values.secrets.slack.signingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jit-bot.fullname" . }}-slack
  labels:
    {{- include "jit-bot.labels" . | nindent 4 }}
type: Opaque
data:
  bot-token: {{ .Values.secrets.slack.botToken | b64enc }}
  signing-secret: {{ .Values.secrets.slack.signingSecret | b64enc }}
{{- end }}