apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jitaccessjobs.jit.rebelops.io
spec:
  group: jit.rebelops.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - accessRequestRef
            - targetCluster
            - duration
            - jitRoleArn
            properties:
              accessRequestRef:
                type: object
                required:
                - name
                - namespace
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                description: Reference to the JITAccessRequest
              targetCluster:
                type: object
                required:
                - name
                - awsAccount
                - region
                properties:
                  name:
                    type: string
                  awsAccount:
                    type: string
                  region:
                    type: string
              duration:
                type: string
                description: Access duration (parsed from request)
              jitRoleArn:
                type: string
                description: ARN of the JIT role to assume
              permissions:
                type: array
                items:
                  type: string
              namespaces:
                type: array
                items:
                  type: string
              cleanupPolicy:
                type: string
                enum: ["OnExpiry", "OnDelete", "Manual"]
                default: "OnExpiry"
                description: When to cleanup the access
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Creating", "Active", "Expiring", "Completed", "Failed"]
              startTime:
                type: string
                format: date-time
              completionTime:
                type: string
                format: date-time
              expiryTime:
                type: string
                format: date-time
              accessEntry:
                type: object
                properties:
                  principalArn:
                    type: string
                  sessionName:
                    type: string
                  credentialsSecretRef:
                    type: object
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
              kubeConfigSecretRef:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
    additionalPrinterColumns:
    - name: Request
      type: string
      jsonPath: .spec.accessRequestRef.name
    - name: Cluster
      type: string
      jsonPath: .spec.targetCluster.name
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Expires
      type: date
      jsonPath: .status.expiryTime
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: jitaccessjobs
    singular: jitaccessjob
    kind: JITAccessJob
    shortNames:
    - jitjob